import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import StoreProvider from "./redux";
import Head from "next/head";
import Link from "next/link";

const inter = Inter({ subsets: ["greek"] });

export const metadata: Metadata = {
  title: "SHS App",
  description: "Generated by create next app",
  icons:{
    icon:"/assets/logo.png"
  }
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
